### PR TITLE
Fixed irregular indentation

### PR DESCRIPTION
**Pull request by ek234**
fixed find_indent() according to #120

### CODE REVIEW

**Comment by lukas-reineke** [comment]
This breaks indentation with just spaces

**Comment by ek234** [comment]
Can you please give me a line that breaks the indentation? It seems to work for me.

**Comment by lukas-reineke** [comment]
any line indented with just spaces, when you turn on `strict_tabs`

**Comment by ek234** [comment]
when `strict_tabs` is set, then only tabs are used for detecting indent right?
So, if the line contains no tabs then the expected behavior should be to not indent anything right?

**Comment by lukas-reineke** [comment]
> when strict_tabs is set, then only tabs are used for detecting indent right?

no this is wrong. Here is the documentation

```
    When on, if there is a single tab in a line, only tabs are used to
    calculate the indentation level.
    When off, both spaces and tabs are used to calculate the indentation
    level.
    Only makes a difference if a line has a mix of tabs and spaces for
    indentation.
```

**Comment by ek234** [comment]
ahh, I see.. I'll push the corrected code in some time

**Comment by lukas-reineke** [comment]
that looks good :+1: 

can you do a couple small things.
1. rename `new_spaces` to just `spaces`
2. format the file with [luafmt](https://github.com/CurtisFenner/luafmt)
3. squash all your commits into one commit

**Comment by ek234** [comment]
First, I added the condition to correct the implementation of `strict_tabs` to the previous code.
However, this made that specific code a bit bulky and unappealing.
So I re-implemented the logic like this:
```
M.find_indent = function(line, shiftwidth, strict_tabs)
    local indent = 0
    local new_spaces = 0
    for ch in line:gmatch(".") do
        if ch == "	" then
            if strict_tabs and indent == 0 and new_spaces ~= 0 then
                return 0, false
	    end
            indent = indent + math.floor( new_spaces / shiftwidth ) + 1
            new_spaces = 0
        elseif ch == " " and ( not strict_tabs or indent == 0 ) then
            new_spaces = new_spaces + 1
        else
            break
        end
    end
    indent = indent + math.floor(new_spaces / shiftwidth)
    return indent, new_spaces % shiftwidth ~= 0
end
```
`new_spaces` is a counter of spaces since the last tab character. `indent` stores the definite number of indents read till now.
Keeping the number of tabs and space indents separately wasn't making any difference in this implementation so I decided to store them together in `indent` to clean the code and reduce calculations.

Implementing of strict_tabs is done in two parts:
1. if the line starts with some spaces and then has at least one tab:
>> if strict_tabs and indent == 0 and new_spaces ~= 0 then
>>     return 0, false
>> end
2. if the line starns with some tabs and then has at least one space
>>  elseif ch == " " and ( not strict_tabs or indent == 0 ) then

Please let me know if there should be any other modifications.

**Comment by ek234** [comment]
okay i will do that.

btw can ya please tell me how to squash the commits to one XD.. I am super new to git.

thanks

**Comment by ek234** [comment]
Ohh, that's super handy. Thanks.

I'll reformat and push.

**Comment by ek234** [comment]
>     2. format the file with [luafmt](https://github.com/CurtisFenner/luafmt)

I did everything you mentioned. One issue I faced was that luafmt converted all the indents in the file to tabs. The rest of the codebase was space indented so I substituted the indent to spaces.
Let me know if you want to keep that as tabs.

**Comment by lukas-reineke** [comment]
sorry i linked the wrong luafmt :man_facepalming: 
i didn't even know there were 2

here is the correct link https://github.com/trixnz/lua-fmt

**Comment by ek234** [comment]
done

**Comment by lukas-reineke** [comment]
I found another small problem

with `strict_tabs` on, a line with first tab indentation, and then space indentation, needs to return `extra = true` (the second value that's returned)

eg. this line `		          fooo` (2 tabs, then spaces)
should look like this

Screen Capture_select-area_20210611142300

but in your PR it looks like this

Screen Capture_select-area_20210611142323

**Comment by ek234** [comment]
I did consider this case in my testing. Here, strict_tabs is on and both spaces and tabs are present. So, according to the docs, only tabs will be considered in the indent.
Therefore, the space which comes after the tabs isn't even a part of the indent. and so, I return extra=false.

I understand that `extra==true` means that there is some more indentation in the line which hasn't been counted in the `indent` variable.
But if a user sets strict_tabs then they are not expecting spaces to be a part of indent in the first place right? Else it will imply a situation where 3tabs is indented the same as 2tabs+4spaces. I felt that a user who set strict tabs would not want this.

Please let me know what you think.

Ps. what color scheme are you using? I really like that shade of green:P

**Comment by lukas-reineke** [comment]
> But if a user sets strict_tabs then they are not expecting spaces to be a part of indent in the first place right? Else it will imply a situation where 3tabs is indented the same as 2tabs+4spaces. I felt that a user who set strict tabs would not want this.

Yes, you are right, kindof.
It should depend on `g:indent_blankline_show_trailing_blankline_indent`

It basically is a trailing indent. It should match what the other lines are doing.

Take for example this code.

```c
#include <stdio.h>

int main(int argc, char *argv[])
{
	printf("test string %s:%s():%d\n",
	       __FILE__, __func__, __LINE__);

	printf("hello");
}
```

in your PR it would look like this with `show_trailing_blankline_indent` on

Screen Capture_select-area_20210611160638

But with it should look like this

Screen Capture_select-area_20210611160717

But with `show_trailing_blankline_indent` off, it makes sense that it looks like you have it now

Screen Capture_select-area_20210611161207

**Comment by lukas-reineke** [comment]
The color scheme is my version of one dark
https://github.com/lukas-reineke/onedark.nvim

**Comment by ek234** [comment]
Oh, I see...

So should I replace
```
[current]          if ((blankline and trail_indent) or extra) and (first_indent or #virtual_text > 0) then
```
with
```
[suggestion]       if ((blankline or extra) and trail_indent) and (first_indent or #virtual_text > 0) then
```
[in file init.lua]

Or is there any case where even though trail_indent is false, extra causes another indent character to be printed?

**Comment by lukas-reineke** [comment]
> So should I replace...

Yes :+1: 

This looks good now.
I don't have that much time today. I'll test a bit more tomorrow, but I think this covers everything now.
Good job

**Comment by ek234** [comment]
aight I squashed everything

thanks

**Comment by ek234** [comment]
Is everything alright?

**Comment by lukas-reineke** [comment]
Yeah sorry just didn't have time
all good
thank you

**Comment by ek234** [comment]
Thanks!!!
This was my first proper PR, and it was really fun working with you.

**Pull request merged**
