### PR TITLE
docs: Make custom background highlighting example automatically set color

### PR DESCRIPTION
**Pull request by brycepg**
based off of existing background color

### CODE REVIEW

**Comment by brycepg** [comment]
Let me know if you think this is a good idea. If you do then maybe I can include it as an option instead of as docs with some pointers

**Comment by brycepg** [comment]
I'm also sure there is a way to trigger the adjustment of colors when the bgcolor or colorscheme changes as well

**Comment by brycepg** [comment]
Here's what it looks like with my colorscheme:

indent-colors-3

indent-colors-3-wombat

**Comment by lukas-reineke** [comment]
Thank you, but I don't think this is an improvement for the documentation. It is much harder to understand what's going on.

And it's also out of scope to add as an option. Getting this color is a one time thing, it shouldn't be computed every time Neovim starts.

**Comment by brycepg** [comment]
Whatever

**Comment by brycepg** [comment]
Whatever will we do if the computer actually computes things

**Comment by brycepg** [comment]
Thanks for letting me know. I think I'm going to fork and change scope

**Pull request closed without merging**
